baseURL = "/"                     
languageCode = "pl"               
defaultContentLanguage = "pl"      # Dodajemy tę linię
title = "Sysmind Blog"            
theme = "PaperMod"                
pagerSize = 10                     

# Parametry motywu
[params]
  title = "Sysmind Blog"          
  subtitle = "Blog o technologii, Linuxie i Cybersecurity"  
  description = "Dzielę się wiedzą o technologii, Linuxie, cybersecurity i więcej!"  
  author = "Michał Adamczyk"      
  keywords = ["Linux", "Cybersecurity", "Technology", "Hugo", "Blog"]
  favicon = "/images/favicon.ico"
  defaultTheme = "light"          
  enableDarkMode = true           
  showReadingTime = true          
  showTOC = true                  

  # Logo
  [params.label]
    icon = "/images/sysmind_logo.jpg"
    iconHeight = 40                  

  # Social Media
  [params.social]
    github = "https://github.com/MichalADA"
    linkedin = "https://www.linkedin.com/in/micha%C5%82-adamczyk-8422a123b"

# Podświetlanie kodu
[markup]
  [markup.highlight]
    noClasses = false
    style = "dracula"             

# Wyjścia generowane przez Hugo
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Menu główne
[menu]
  [[menu.main]]
    identifier = "about"
    name = "O Mnie"
    url = "/posts/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projekty"
    url = "/posts/projects/"
    weight = 2