baseURL = "/"                     # Bazowy URL strony
languageCode = "pl"               # Kod języka
title = "Sysmind Blog"            # Globalny tytuł strony
theme = "PaperMod"                # Nazwa motywu
pagerSize = 10                     # Liczba wpisów na stronę

# Parametry motywu
[params]
  title = "Sysmind Blog"          # Tytuł strony
  subtitle = "Blog o technologii, Linuxie i Cybersecurity"  # Podtytuł
  description = "Dzielę się wiedzą o technologii, Linuxie, cybersecurity i więcej!"  # Opis strony
  author = "Michał Adamczyk"      # Imię i nazwisko autora
  keywords = ["Linux", "Cybersecurity", "Technology", "Hugo", "Blog"] # Słowa kluczowe
  favicon = "/images/favicon.ico" # Ścieżka do favikony
  defaultTheme = "light"          # Domyślny motyw (light/dark)
  enableDarkMode = true           # Włącz tryb ciemny
  showReadingTime = true          # Pokaż czas czytania
  showTOC = true                  # Włącz tabelę treści

  # Logo
  [params.label]
    icon = "/images/sysmind_logo.jpg" # Ścieżka do logo bloga
    iconHeight = 40                  # Wysokość logo w pikselach

  # Social Media
  [params.social]
    github = "https://github.com/MichalADA"
    linkedin = "https://www.linkedin.com/in/micha%C5%82-adamczyk-8422a123b"

# Podświetlanie kodu
[markup]
  [markup.highlight]
    noClasses = false
    style = "dracula"             # Styl podświetlania kodu

# Wyjścia generowane przez Hugo
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Menu główne
[menu]
  [[menu.main]]
    identifier = "about"
    name = "O Mnie"
    url = "/posts/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projekty"
    url = "/posts/projects/"
    weight = 2
